name: jalan
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # PyTorch + CUDA (cocok untuk RTX 3050)
  - pytorch=2.2.*
  - torchvision=0.17.*
  - torchaudio=2.2.*
  - pytorch-cuda=11.8

  # Basic scientific & ML
  - numpy
  - pandas
  - scikit-learn
  - pillow

  # Utilities
  - tqdm
  - matplotlib
  - seaborn

  # Optional, useful
  - opencv
  - pip

  - pip:
      - imutils
